Show simple error message in Vim for gofmt
tweekmonster/gofmt.vim pull request #3
Opened 2017-05-30 03:57 UTC by orklann

This PR is relative to #2 
Thanks for your nice working on Vim plugins.

2017-06-08 12:11 UTC, tweekmonster commented
Thanks.  Could you make this optional through `g:gofmt_display_errors`?  I also thought it would display the actual error message from the shell command so the user knows how to fix the problem.

2017-06-09 10:07 UTC, orklann commented
I have made two commits, one for g:gofmt_display_errors, and one for displaying actual full shell command message.

2017-06-18 05:22 UTC, tweekmonster requested changes
I'm very sorry for the delayed reply!  After these changes are made, I will merge this as soon as I get the notification.

2017-06-18 05:22 UTC, tweekmonster commented on autoload/gofmt.vim
> +    if g:gofmt_display_errors
Change this to `if get(g:, 'gofmt_display_errors', 0)`.  Otherwise it will cause an error when the variable doesn't exist.

2017-06-18 05:22 UTC, tweekmonster commented on autoload/gofmt.vim
> +      echo output
Please add `echohl None`

2017-06-19 09:30 UTC, orklann commented on autoload/gofmt.vim
> +    if g:gofmt_display_errors
I made a commit to do this.

2017-06-19 09:31 UTC, orklann commented on autoload/gofmt.vim
> +      echo output
Modified.

2017-06-19 20:32 UTC, tweekmonster commented on autoload/gofmt.vim
> +      echo output
Oh sorry, I meant it should look like:

```vim
echohl ErrorMsg
echo output
echohl None
```

It's to reset the message highlight.

2017-06-20 03:02 UTC, orklann commented on autoload/gofmt.vim
> +      echo output
Sorry, please check the newest commit, it should be ok.

2017-06-20 04:44 UTC, merged

2017-06-20 04:44 UTC, tweekmonster commented
Thanks!